/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jindemo_jindemo_HelloWorld */

#ifndef _Included_com_jindemo_jindemo_HelloWorld
#define _Included_com_jindemo_jindemo_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jindemo_jindemo_HelloWorld
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jindemo_jindemo_HelloWorld_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
